### ISSUE TITLE
Error when running the script

### ISSUE THREAD

**Issue by salmander** [bobbyromeo/SyncToSD2#1]
Hi, 
I get this error when running the script. How can I debug this?

```
command substitution: line 90: syntax error near unexpected token `('
/Users/salmanahmed/workspace/sdcard-wifi-sync/SyncToSD2.sh: command substitution: line 90: `comm -13 <(echo -e "${REMOTELIST}" | ${SORT}) <(echo "${GCODE}" | ${SED} -e 's/[[:space:]]*$//' | ${SORT})'
/Users/salmanahmed/workspace/sdcard-wifi-sync/SyncToSD2.sh: command substitution: line 91: syntax error near unexpected token `('
/Users/salmanahmed/workspace/sdcard-wifi-sync/SyncToSD2.sh: command substitution: line 91: `comm -23 <(echo -e "${REMOTELIST}" | ${SORT}) <(echo "${GCODE}" | ${SED} -e 's/[[:space:]]*$//' | ${SORT})'
/Users/salmanahmed/workspace/sdcard-wifi-sync/SyncToSD2.sh: command substitution: line 92: syntax error near unexpected token `('
/Users/salmanahmed/workspace/sdcard-wifi-sync/SyncToSD2.sh: command substitution: line 92: `comm -12 <(echo -e "${REMOTELIST}" | ${SORT}) <(echo "${GCODE}" | ${SED} -e 's/[[:space:]]*$//'| ${SORT})'
```

**Comment by bobbyromeo** [comment]
I'm not exactly sure what's causing this without seeing the script and how you modified it. 
Sadly, I'm not able to reproduce the problem on my end. Did you download the "raw" version of the script? Can you simply run that line from the command line and see if it produces the same error? Also that line uses the sort/sed binaries, can you verify if you have them on your system?

**Comment by salmander** [comment]
Modified just three variables as mentioned at the top of the script.
```
LPATH="/Users/salmanahmed/Documents/G_Code/"
RPATH="/G_Code"
FLASHAIR="192.168.1.200"
```

Also, changed `DEBUG=1` to see if I can identify the problem.

```
which sort
/usr/bin/sort

which sed
/usr/bin/sed

**Comment by salmander** [comment]
No, what do you mean by the raw version? I just copied pasted the script and changed the variables.

**Comment by bobbyromeo** [comment]
I mean if you don't select the raw version of the file (by clicking the raw button) and simply copy/paste it may introduce unwanted characters that affect the script's functionality. This is the link of the file that I would save to disk: https://raw.githubusercontent.com/bobbyromeo/SyncToSD2/master/SyncToSD2.sh

**Comment by salmander** [comment]
> I mean if you don't select the raw version of the file (by clicking the raw button) and simply copy/paste it may introduce unwanted characters that affect the script's functionality. This is the link of the file that I would save to disk: https://raw.githubusercontent.com/bobbyromeo/SyncToSD2/master/SyncToSD2.sh

Yup this is how I copied it.

**Comment by salmander** [comment]
I can try manually running it but the statement has a couple of variables i.e. `REMOTELIST`, `SORT`, `GCODE` and `SED`. Let me resolve that and try.

**Comment by bobbyromeo** [comment]
The next thing I'd try is to run commands via the command line while substituting the variables in ${..} with their proper values.

First though, check if curl is installed:
`which curl`

If not: https://brewinstall.org/install-curl-on-mac-with-brew/

Next see if you're able to connect to the flashair  card at all with this command:

`/usr/bin/curl --silent "http://192.168.1.200/command.cgi?op=100&DIR=/G_Code"`

It should spit out all files in the /G_Code directory on the card.

This should give us some more insight as to where the problem lies.

**Comment by salmander** [comment]
Just a quick update, the script works. Haven't figured out what was the last change that made it work. I should have checked out the repo to track changes. Thanks for your help and for this script.
